"""empty message

Revision ID: bb91fb332c36
Revises: f2bac0a1cdaa
Create Date: 2018-02-13 17:08:09.313113

"""
from alembic import op
import sqlalchemy as sa
from GeoHealthCheck.migrations import alembic_helpers


# revision identifiers, used by Alembic.
revision = 'bb91fb332c36'
down_revision = '2638c2a40625' 
branch_labels = None
depends_on = None


def upgrade():
    if not alembic_helpers.tables_exist(['recipient']):
        print('creating Recipient table(s)')

        # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('recipient',
                        sa.Column('id', sa.Integer(), nullable=False),
                        sa.Column('channel', sa.Enum('email'), nullable=False),
                        sa.Column('location', sa.Text(), nullable=False),
                        sa.PrimaryKeyConstraint('id')
        )

        op.create_table('resourcenotification',
                        sa.Column('resource_id', sa.Integer(), nullable=False),
                        sa.Column('recipient_id', sa.Integer(), nullable=False),
                        sa.ForeignKeyConstraint(['resource_id'], ['resource.identifier'], ),
                        sa.ForeignKeyConstraint(['recipient_id'], ['recipient.id'], ),
                        sa.PrimaryKeyConstraint('resource_id', 'recipient_id')
        )
        # ### end Alembic commands ###
    else:
        print('Tables for recipient support already present, will not create them')


def downgrade():
    op.drop_table('resourcenotification')
    op.drop_table('recipient')
