---
apiVersion: 'v1'
kind: 'Secret'
metadata:
  name: {{ printf "%s-secrets" (include "geohealthcheck.fullname" .) | squote }}
  labels:
    {{- include "geohealthcheck.labels" . | nindent 4 }}
type: 'Opaque'
data:
  SECRET_KEY: {{ .Values.geohealthcheck.auth.secret | b64enc | squote }}
  {{- if and .Values.geohealthcheck.smtpPassword .Values.geohealthcheck.smtpEnabled }}
  GHC_SMTP_PASSWORD: {{ .Values.geohealthcheck.smtpPassword | b64enc | squote }}
  {{- end }}
  SQLALCHEMY_DATABASE_URI: {{ .Values.geohealthcheck.databaseUri | b64enc | squote }}
