name: Docker Build and Push to DockerHub

# Author: Just van den Broecke
# Controls when the action will run. Triggers the workflow on push
# events and PRs but only for the master branch. Runs GHC unit tests as well.
#
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  # Single job now to build Docker Image and push to DockerHub
  push_to_registry:

    name: Build and Push Docker Image to Docker Hub

    runs-on: ubuntu-latest

    # v2 https://github.com/docker/build-push-action/blob/master/UPGRADE.md
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=geopython/geohealthcheck
          VERSION=latest
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE}:${VERSION}"
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker Build, Docker Push (GH Push only)
        uses: docker/build-push-action@v2
        with:
          context: .
          load: true
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.prep.outputs.tags }}
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}

      - name: Unit Tests With Docker Image
        run: docker run  --entrypoint "/run-tests.sh" geopython/geohealthcheck:${{ steps.prep.outputs.version }}

      - name: Push to Docker repo (GH Push only)
        if: ${{ github.event_name == 'push' }}
        run: docker push geopython/geohealthcheck:${{ steps.prep.outputs.version }}
